
server.port = 8888
logging.config = classpath:log4j2-spring.xml

spring.application.name=corgiApp
spring.dubbo.registry=zookeeper://127.0.0.1:2181
spring.redis.host=localhost
spring.redis.port=6379

aliyun.accessKeyId=LTAI4Fwu7uCt6ijGW7rLWbqQ
aliyun.AccessKeySecret=Kxl0JLGjrIyeSc94ZZKGiUTUCSZLx3
aliyun.bucketName=corgi-pic
aliyun.endpoint=oss-cn-beijing.aliyuncs.com
aliyun.role.arn=acs:ram::1913874992729850:role/corgimanager
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=test
#spring.rabbitmq.password=test
# 开启ACK
#spring.rabbitmq.listener.direct.acknowledge-mode=manual
#spring.rabbitmq.listener.simple.acknowledge-mode=manual

