spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mysql://10.240.106.104:3306/dsp_shoe_test
spring.datasource.username=dev
spring.datasource.password=123456

#初始化连接
spring.datasource.initial-size=100
#最大空闲连接
spring.datasource.max-idle=200
#最小空闲连接
spring.datasource.min-idle=5
#最大连接数量
spring.datasource.max-active=500
#是否在自动回收超时连接的时候打印连接的超时错误
spring.datasource.log-abandoned=true
#是否自动回收超时连接
spring.datasource.remove-abandoned=true
#超时时间(以秒数为单位)
spring.datasource.remove-abandoned-timeout=180
##<!-- 超时等待时间以毫秒为单位 60000毫秒/1000等于60秒 -->
spring.datasource.max-wait=60000
spring.datasource.test-while-idle=true
#检测数据库的查询语句
spring.datasource.validation-query=select 1 from dual
#每隔五分钟检测空闲超过10分钟的连接
spring.datasource.min-evictable-idle-time-millis=600000
spring.datasource.time-between-eviction-runs-millis=300000

server.tomcat.remote_ip_header=x-forwarded-for

server.port = 8888

spring.redis.host=10.240.106.13
spring.redis.port=6379
spring.redis.password=123456

spring.rabbitmq.host=10.240.106.12
spring.rabbitmq.port=5672
spring.rabbitmq.username=test
spring.rabbitmq.password=test
# 开启ACK
spring.rabbitmq.listener.direct.acknowledge-mode=manual
spring.rabbitmq.listener.simple.acknowledge-mode=manual


qcloud.region = ap-beijing
qcloud.bucketname = dasuan-app-1255389510
qcloud.secretID = AKIDRp08ViYbGxW6bPje3GH6mIcklpiPqITT
qcloud.secretKey = xDOPEvQjtrgJ0465ttmU0KTaCsaKytkQ

cros.allowedOrigins = *
cros.maxAge = 3600

DASUAN_TOEKN = 7e06a94fc3f943268fa5a0d2354793cf,59c0cde813aa4c799a3c88baf02a3e16,d567fa3aadf04dbea5fd20315b979cd8,02wfvtwfpm91h0r14ptttlq3gs0cp3kp,6caaf58175aa48cf9472dd7993458b75

firstOrderPush.appid = 113
firstOrderPush.code = 8e53235a5205b3d674608e05160d1b5e
firstOrderPush.url = https://a4aae758.app.hillinsight.com/list_sale_detail?store_id=

es.host = 10.240.106.104
es.port = 9200
es.scheme = http

