
server.port = 8888
server.tomcat.max-threads = 2000
spring.datasource.tomcat.max-active=500
logging.config = classpath:log4j2-spring.xml

spring.application.name=corgiApp
spring.dubbo.registry=zookeeper://172.19.22.140:2181
spring.redis.host=172.19.22.140
spring.redis.port=6379
spring.dubbo.consumer.timeout=15000

aliyun.accessKeyId=LTAI4Fwu7uCt6ijGW7rLWbqQ
aliyun.AccessKeySecret=Kxl0JLGjrIyeSc94ZZKGiUTUCSZLx3
aliyun.bucketName=corgi-pic
aliyun.sts.endpoint=sts.cn-beijing.aliyuncs.com
aliyun.endpoint=oss-cn-beijing.aliyuncs.com
aliyun.role.arn=acs:ram::1913874992729850:role/corgimanager

easemob.orgname=1101200130181163
easemob.appname=corgi
spring.rabbitmq.host=172.19.22.140
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin


